In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from tensorflow.keras.models import load_model
import pickle

In [6]:
data = pd.read_csv("Churn_Modelling.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [8]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

In [11]:
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']
print(X)
print(y)

      CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1
1             608       0   41       1   83807.86              1          0
2             502       0   42       8  159660.80              3          1
3             699       0   39       1       0.00              2          0
4             850       0   43       2  125510.82              1          1
...           ...     ...  ...     ...        ...            ...        ...
9995          771       1   39       5       0.00              2          1
9996          516       1   35      10   57369.61              1          1
9997          709       0   36       7       0.00              1          0
9998          772       1   42       3   75075.31              2          1
9999          792       0   28       4  130142.79              1          1

      IsActiveMember  Exited  Geography_France  Geography_Germany  \
0                  1       1               1.0                0.0
1                  1       0               0.0                0.0
2                  0       1               1.0                0.0
3                  0       0               1.0                0.0
4                  1       0               0.0                0.0
...              ...     ...               ...                ...
9995               0       0               1.0                0.0
9996               1       0               1.0                0.0
9997               1       1               1.0                0.0
9998               0       1               0.0                1.0
9999               0       0               1.0                0.0

      Geography_Spain
0                 0.0
1                 1.0
2                 0.0
3                 0.0
4                 1.0
...               ...
9995              0.0
9996              0.0
9997              0.0
9998              0.0
9999              0.0

[10000 rows x 12 columns]
0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Regressoin Problem Statement

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1], )),
    Dense(32, activation='relu'),
    Dense(1) # default activation fn is Linear Activation Function
])

# compile model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
# logs, tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressions/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [21]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [22]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 101020.7344 - mae: 101020.7344 - val_loss: 97991.1641 - val_mae: 97991.1641
Epoch 2/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - loss: 100532.5859 - mae: 100532.5859 - val_loss: 97002.6641 - val_mae: 97002.6641
Epoch 3/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 98770.5312 - mae: 98770.5312 - val_loss: 94388.7109 - val_mae: 94388.7109
Epoch 4/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - loss: 95168.5703 - mae: 95168.5703 - val_loss: 89817.9766 - val_mae: 89817.9766
Epoch 5/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 89644.5391 - mae: 89644.5391 - val_loss: 83444.5703 - val_mae: 83444.5703
Epoch 6/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 82544.6562 - mae: 82544.6562 - val_loss: 75947.4219 - val_mae: 75947.4219
Epoch 7/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - loss: 74672.5625 - mae: 74672.5625 - val_loss: 68281.1562 - val_mae: 68281.1562
Epoch 8/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 67087.5781 - mae: 67087.5781 - val_loss: 61524.1445 - val_mae: 61524.1445
Epoch 9/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 60791.5352 - mae: 60791.5352 - val_loss: 56401.1133 - val_mae: 56401.1133
Epoch 10/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 56251.9453 - mae: 56251.9453 - val_loss: 53051.8945 - val_mae: 53051.8945
Epoch 11/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 53421.1680 - mae: 53421.1680 - val_loss: 51207.0781 - val_mae: 51207.0781
Epoch 12/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 51925.1953 - mae: 51925.1953 - val_loss: 50413.7617 - val_mae: 50413.7617
Epoch 13/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 51192.2188 - mae: 51192.2188 - val_loss: 50169.1406 - val_mae: 50169.1406
Epoch 14/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - loss: 50872.2930 - mae: 50872.2930 - val_loss: 50089.9922 - val_mae: 50089.9922
Epoch 15/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 50724.4531 - mae: 50724.4531 - val_loss: 50047.0117 - val_mae: 50047.0117
Epoch 16/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 50630.1406 - mae: 50630.1406 - val_loss: 50011.1328 - val_mae: 50011.1328
Epoch 17/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 50557.8320 - mae: 50557.8320 - val_loss: 49983.3633 - val_mae: 49983.3633
Epoch 18/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - loss: 50498.0391 - mae: 50498.0391 - val_loss: 49956.4414 - val_mae: 49956.4414
Epoch 19/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - loss: 50440.1250 - mae: 50440.1250 - val_loss: 49924.3750 - val_mae: 49924.3750
Epoch 20/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - loss: 50396.1602 - mae: 50396.1602 - val_loss: 49893.1016 - val_mae: 49893.1016
Epoch 21/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 50351.7500 - mae: 50351.7500 - val_loss: 49871.1758 - val_mae: 49871.1758
Epoch 22/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - loss: 50310.1641 - mae: 50310.1641 - val_loss: 49848.0391 - val_mae: 49848.0391
Epoch 23/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 50271.8477 - mae: 50271.8477 - val_loss: 49822.2773 - val_mae: 49822.2773
Epoch 24/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 50238.1406 - mae: 50238.1406 - val_loss: 49801.3086 - val_mae: 49801.3086
Epoch 25/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 50210.3164 - mae: 50210.3164 - val_loss: 49782.2188 - val_mae: 49782.2188
Epoch 26/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 50181.1484 - mae: 50181.1484 - val_loss: 49768.6641 - val_mae: 49768.6641
Epoch 27/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 50151.8086 - mae: 50151.8086 - val_loss: 49759.4180 - val_mae: 49759.4180
Epoch 28/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 50128.8594 - mae: 50128.8594 - val_loss: 49737.7070 - val_mae: 49737.7070
Epoch 29/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 50108.2617 - mae: 50108.2617 - val_loss: 49727.7930 - val_mae: 49727.7930
Epoch 30/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 50086.7266 - mae: 50086.7266 - val_loss: 49712.2344 - val_mae: 49712.2344
Epoch 31/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 50063.1172 - mae: 50063.1172 - val_loss: 49701.9297 - val_mae: 49701.9297
Epoch 32/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 50045.2031 - mae: 50045.2031 - val_loss: 49701.3711 - val_mae: 49701.3711
Epoch 33/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 50028.4805 - mae: 50028.4805 - val_loss: 49671.9375 - val_mae: 49671.9375
Epoch 34/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 50013.9883 - mae: 50013.9883 - val_loss: 49664.2891 - val_mae: 49664.2891
Epoch 35/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49997.2695 - mae: 49997.2695 - val_loss: 49653.8164 - val_mae: 49653.8164
Epoch 36/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49982.7305 - mae: 49982.7305 - val_loss: 49636.7070 - val_mae: 49636.7070
Epoch 37/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 49964.4961 - mae: 49964.4961 - val_loss: 49629.1133 - val_mae: 49629.1133
Epoch 38/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49952.7344 - mae: 49952.7344 - val_loss: 49631.6797 - val_mae: 49631.6797
Epoch 39/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49937.8594 - mae: 49937.8594 - val_loss: 49629.1523 - val_mae: 49629.1523
Epoch 40/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 49926.6953 - mae: 49926.6953 - val_loss: 49623.1758 - val_mae: 49623.1758
Epoch 41/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 49913.2188 - mae: 49913.2188 - val_loss: 49612.4570 - val_mae: 49612.4570
Epoch 42/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 49899.3945 - mae: 49899.3945 - val_loss: 49606.2852 - val_mae: 49606.2852
Epoch 43/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 49888.7539 - mae: 49888.7539 - val_loss: 49605.3789 - val_mae: 49605.3789
Epoch 44/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 49877.8359 - mae: 49877.8359 - val_loss: 49596.5352 - val_mae: 49596.5352
Epoch 45/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49869.6562 - mae: 49869.6562 - val_loss: 49599.3203 - val_mae: 49599.3203
Epoch 46/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 49857.3242 - mae: 49857.3242 - val_loss: 49602.4688 - val_mae: 49602.4688
Epoch 47/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49847.2969 - mae: 49847.2969 - val_loss: 49603.1602 - val_mae: 49603.1602
Epoch 48/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49835.8867 - mae: 49835.8867 - val_loss: 49590.2188 - val_mae: 49590.2188
Epoch 49/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 49829.0117 - mae: 49829.0117 - val_loss: 49589.0703 - val_mae: 49589.0703
Epoch 50/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 49819.7383 - mae: 49819.7383 - val_loss: 49584.7383 - val_mae: 49584.7383
Epoch 51/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49811.0703 - mae: 49811.0703 - val_loss: 49589.2188 - val_mae: 49589.2188
Epoch 52/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 49800.9727 - mae: 49800.9727 - val_loss: 49575.8359 - val_mae: 49575.8359
Epoch 53/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49795.1680 - mae: 49795.1680 - val_loss: 49576.2148 - val_mae: 49576.2148
Epoch 54/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 49789.9609 - mae: 49789.9609 - val_loss: 49570.9531 - val_mae: 49570.9531
Epoch 55/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49780.9180 - mae: 49780.9180 - val_loss: 49580.0625 - val_mae: 49580.0625
Epoch 56/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 49773.6875 - mae: 49773.6875 - val_loss: 49564.8164 - val_mae: 49564.8164
Epoch 57/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49765.4336 - mae: 49765.4336 - val_loss: 49566.0312 - val_mae: 49566.0312
Epoch 58/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 49757.6406 - mae: 49757.6406 - val_loss: 49563.9023 - val_mae: 49563.9023
Epoch 59/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - loss: 49750.4727 - mae: 49750.4727 - val_loss: 49559.7812 - val_mae: 49559.7812
Epoch 60/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49746.2539 - mae: 49746.2539 - val_loss: 49554.8086 - val_mae: 49554.8086
Epoch 61/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49736.4805 - mae: 49736.4805 - val_loss: 49557.0234 - val_mae: 49557.0234
Epoch 62/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 49733.2070 - mae: 49733.2070 - val_loss: 49544.8828 - val_mae: 49544.8828
Epoch 63/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49726.9883 - mae: 49726.9883 - val_loss: 49560.7617 - val_mae: 49560.7617
Epoch 64/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49719.6094 - mae: 49719.6094 - val_loss: 49547.5547 - val_mae: 49547.5547
Epoch 65/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49716.9180 - mae: 49716.9180 - val_loss: 49550.3516 - val_mae: 49550.3516
Epoch 66/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49709.4922 - mae: 49709.4922 - val_loss: 49539.6602 - val_mae: 49539.6602
Epoch 67/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - loss: 49701.0234 - mae: 49701.0234 - val_loss: 49548.4844 - val_mae: 49548.4844
Epoch 68/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 49698.7305 - mae: 49698.7305 - val_loss: 49547.1367 - val_mae: 49547.1367
Epoch 69/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 49694.7500 - mae: 49694.7500 - val_loss: 49536.7461 - val_mae: 49536.7461
Epoch 70/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49690.5586 - mae: 49690.5586 - val_loss: 49549.8047 - val_mae: 49549.8047
Epoch 71/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - loss: 49683.0234 - mae: 49683.0234 - val_loss: 49545.3906 - val_mae: 49545.3906
Epoch 72/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 49683.4531 - mae: 49683.4531 - val_loss: 49535.8320 - val_mae: 49535.8320
Epoch 73/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 49671.6367 - mae: 49671.6367 - val_loss: 49548.0156 - val_mae: 49548.0156
Epoch 74/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49669.1953 - mae: 49669.1953 - val_loss: 49543.3945 - val_mae: 49543.3945
Epoch 75/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49663.4141 - mae: 49663.4141 - val_loss: 49538.3164 - val_mae: 49538.3164
Epoch 76/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49661.2031 - mae: 49661.2031 - val_loss: 49542.1133 - val_mae: 49542.1133
Epoch 77/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 49655.2852 - mae: 49655.2852 - val_loss: 49538.5664 - val_mae: 49538.5664
Epoch 78/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 49651.6641 - mae: 49651.6641 - val_loss: 49536.4414 - val_mae: 49536.4414
Epoch 79/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 49645.4883 - mae: 49645.4883 - val_loss: 49538.1914 - val_mae: 49538.1914
Epoch 80/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49643.7578 - mae: 49643.7578 - val_loss: 49534.8008 - val_mae: 49534.8008
Epoch 81/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - loss: 49637.5742 - mae: 49637.5742 - val_loss: 49539.0000 - val_mae: 49539.0000
Epoch 82/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 49631.1992 - mae: 49631.1992 - val_loss: 49537.1328 - val_mae: 49537.1328
Epoch 83/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 49629.8398 - mae: 49629.8398 - val_loss: 49542.7617 - val_mae: 49542.7617
Epoch 84/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 49628.4648 - mae: 49628.4648 - val_loss: 49539.1797 - val_mae: 49539.1797
Epoch 85/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49622.5000 - mae: 49622.5000 - val_loss: 49549.2617 - val_mae: 49549.2617
Epoch 86/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 49617.2930 - mae: 49617.2930 - val_loss: 49549.3242 - val_mae: 49549.3242
Epoch 87/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - loss: 49614.0195 - mae: 49614.0195 - val_loss: 49551.3359 - val_mae: 49551.3359
Epoch 88/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 49613.7500 - mae: 49613.7500 - val_loss: 49553.7930 - val_mae: 49553.7930
Epoch 89/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 49608.5859 - mae: 49608.5859 - val_loss: 49552.3047 - val_mae: 49552.3047
Epoch 90/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 49602.3750 - mae: 49602.3750 - val_loss: 49546.3086 - val_mae: 49546.3086

In [23]:
%load_ext tensorboard

In [24]:
%tensorboard --logdir regressions/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/Users/y0a02i0/Documents/Udemy/Complete Gen AI Course with Langchain and HuggingFace/.venv/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/Users/y0a02i0/Documents/Udemy/Complete Gen AI Course with Langchain and HuggingFace/.venv/lib/python3.13/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/y0a02i0/Documents/Udemy/Complete Gen AI Course with Langchain and HuggingFace/.venv/lib/python3.13/site-packages/tensorboard/default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [25]:
# Tensorboard not working here due to python kernel issue, hence using google colab by uploading logs zip file there - https://colab.research.google.com/drive/1hnSjjy-NlWYIOZF10XvSl3b0u49gZ7zq#scrollTo=Pq7GNdFDwpiU

In [26]:
# evaluate model on test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}")
print(f"Test MAE: {test_mae}")

104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 49534.8008 - mae: 49534.8008
Test Loss: 49534.80078125
Test MAE: 49534.80078125

In [27]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.